configfile: "config/config.yml"

# Classic filter
include: "rules/common.smk"
include: "rules/rdmmap.smk"
include: "rules/prepare_rdm_Neinputs.smk"

wildcard_constraints:
    chr = "|".join(get_chr_list(config["fai_path"])),
    prefix = config["final_prefix"],

rule all:
    input:
        get_output()