from os import path

configfile: "config/config.yml"

# Classic filter
include: "rules/common.smk"
include: "rules/filter_callability.smk"
include: "rules/prepare_strway_plot.smk"
include: "rules/prepare_smcpp.smk"
include: "rules/prepare_vcf.smk"

# Force chr name matching in paths
wildcard_constraints:
    chr = "|".join(get_chr_list(config["fai_path"])),
    sfs_params_method = "|".join(["ml", "max"]),
    prefix = config["final_prefix"],
    rec_quant = "|".join(["rec1","rec2","rec3"]), # 1 = < 33%, 2 = >33% et <66%, 3= > 66%
    sampling_method = "|".join(["small","max","ml","strict"])

if config["recombination"]:
    module recombination:
        snakefile:
            "modules/recombination/Snakefile"
        config:
            config
use rule * from recombination as rec_*

if config["density"]:
    module density:
        snakefile:
            "modules/gene_density/Snakefile"
        config:
            config
use rule * from density as density_*

rule all:
    input:
        get_output()
    default_target: True