configfile: "config/config.yml"
include: "rules/common.smk"
include: "rules/filter_callability.smk"
include: "rules/prepare_Neinputs.smk"

wildcard_constraints:
    chr = "|".join(get_chr_list(config["fai_path"])),
    prefix = config["final_prefix"],
    call_filter = "|".join(["small", "ml", "strict"]),
    out = []

FINAL_PREFIX = config["final_prefix"]
CHROMOSOMES: list = get_chr_list(config["fai_path"])
CALLABILITY_FILTER: list = ["small", "ml", "strict"]

rule all:
    input:
        # Stairway Plot inputs
        expand("results/callability/ne_inference/strway_plt/{call_filter}/{prefix}.SNPS.NA.{call_filter}.{chr}.blueprint", prefix=FINAL_PREFIX, chr=CHROMOSOMES, call_filter=CALLABILITY_FILTER),
        # SMC++ inputs
        expand("results/callability/ne_inference/smcpp/{call_filter}/{prefix}.SNPS.NA.{call_filter}.{chr}.smc.gz", prefix=FINAL_PREFIX, chr=CHROMOSOMES, call_filter=CALLABILITY_FILTER)