configfile: "config/config.yml"
include: "rules/common.smk"
include: "rules/split_by_geneD.smk"
include: "rules/prepare_Neinputs.smk"

wildcard_constraints:
    chr = "|".join(get_chr_list(config["fai_path"])),
    prefix = config["final_prefix"],
    density = "|".join(["lowD","highD"])


rule all:
    input:
        get_output()