configfile: "config/config.yml"
include: "rules/common.smk"
include: "rules/split_by_rec.smk"
include: "rules/prepare_Neinputs.smk"

wildcard_constraints:
    chr = "|".join(get_chr_list(config["fai_path"])),
    prefix = config["final_prefix"],
    rec = "|".join(["rec1","rec2","rec3"])

FINAL_PREFIX = config["final_prefix"]
CHROMOSOMES: list = get_chr_list(config["fai_path"])
REC_QUANTILES: list = ["rec1","rec2","rec3"]

rule all:
    input:
        # Plot sfs
        # expand("results/rec/sfs/{rec}/{prefix}.{rec}.{chr}.png", prefix=FINAL_PREFIX, rec=REC_QUANTILES, chr=CHROMOSOMES),
        # Stairway Plot inputs
        expand("results/rec/ne_inference/smcpp/{rec}/{prefix}.{rec}.{chr}.smc.gz", prefix=FINAL_PREFIX, rec=REC_QUANTILES, chr=CHROMOSOMES),
        # SMC++ inputs
        expand("results/rec/ne_inference/strway_plt/{rec}/{prefix}.{rec}.{chr}.blueprint", prefix=FINAL_PREFIX, rec=REC_QUANTILES, chr=CHROMOSOMES)
