configfile: "config/config.yml"
include: "rules/common.smk"
include: "rules/recmap.smk"
include: "rules/prepare_Neinputs.smk"

wildcard_constraints:
    chr = "|".join(get_chr_list(config["fai_path"])),
    prefix = config["final_prefix"],
    rec_quant = "|".join(["rec1","rec2","rec3"])

chromosomes: list = get_chr_list(config["fai_path"])

rule all:
    input:
        get_output()