# Config
vcf_path: "/shared/projects/plant_lewontin_paradox/ne/data/cgrandiflora/vcf/cgrandiflora_PRJNA275635.SNPS.NA.KB870812.1.vcf.gz"
fai_path: "/shared/projects/plant_lewontin_paradox/ne/data/cgrandiflora/stats/GCA_000375325.1.KB870812.1.fai"
bed_path: "/shared/projects/plant_lewontin_paradox/ne/data/cgrandiflora/cgrandiflora_PRJNA275635.raw.KB870812.1.callable.bed"
final_prefix: "cgrandiflora_PRJNA275635"
easySFS_path: "/shared/projects/plant_lewontin_paradox/softwares/easySFS/easySFS.py"
stairway_plot_dir: "/shared/projects/plant_lewontin_paradox/softwares/stairway_plot_es"
smcpp: "/shared/projects/plant_lewontin_paradox/softwares/smcpp.sif"
mutation_rate: "7e-9"
generation_time: 1

# Recombination module
recombination: False
recmap: ""

# Density
density: True
annotation: "/shared/projects/plant_lewontin_paradox/vcf_processing/data/toy_example/GCF_000375325.1_Caprub1_0_genomic.KB870812.1.gff"
window_size: 10000

stop: False # True to do only density module