# Config
vcf_path: "/projects/plantlp/03_NE_INFERENCE/data/cgrandiflora/original_data/cgrandiflora_PRJNA275635_raw.vcf.gz"
fai_path: "/projects/plantlp/00_DATA/data/cgrandiflora/GCA_000375325.1.chr1.fna.fai"
bed_path: "/projects/plantlp/03_NE_INFERENCE/data/cgrandiflora/original_data/cgrandiflora_PRJNA275635_callable_all_samples.bed"
pop_path: "/projects/plantlp/03_NE_INFERENCE/data/cgrandiflora/pop/cgrandiflora_PRJNA275635.10.txt"
final_prefix: "test"
easySFS_path: "/projects/plantlp/softwares/easySFS/easySFS.py"
stairway_plot_dir: "/projects/plantlp/softwares/strway_plot/stairway_plot_es"
smcpp: "/projects/plantlp/softwares/smcpp/smcpp.sif"
mutation_rate: "7e-9"
generation_time: 1

# Callability
callability: False

# Recombination module
recombination: False
recmap: ""

# Density
density: False
annotation: ""
window_size: 100000

stop: False # True to do only density module