executor: slurm
use-conda: True
jobs: 50 # Have up to N jobs submitted at any given time
latency-wait: 200 # Wait N seconds for output files due to latency
retries: 1 # Retry jobs N times.

# These resources will be applied to all rules. Can be overriden on a per-rule basis below.
default-resources:
  mem_mb: attempt * 5000
  slurm_partition: "fast"
  slurm_account: "plant_lewontin_paradox"
  runtime: 240 # (In minutes)
  cpus_per_task: 2

set-threads:
  split_vcf: 1
set-resources:
  sfs_projection:
    mem_mb: attempt * 50000
    slurm_partition: "fast"
    slurm_account: "plant_lewontin_paradox"
    runtime: 720 # (In minutes)
    cpus_per_task: 16

  sfs_projection_na:
    mem_mb: attempt * 50000
    slurm_partition: "fast"
    slurm_account: "plant_lewontin_paradox"
    runtime: 720 # (In minutes)
    cpus_per_task: 16

  sfs_max_ml:
    mem_mb: attempt * 50000
    slurm_partition: "fast"
    slurm_account: "plant_lewontin_paradox"
    runtime: 720 # (In minutes)
    cpus_per_task: 16

  sfs_small:
    mem_mb: attempt * 50000
    slurm_partition: "fast"
    slurm_account: "plant_lewontin_paradox"
    runtime: 720 # (In minutes)
    cpus_per_task: 16

  sfs_strict:
    mem_mb: attempt * 50000
    slurm_partition: "fast"
    slurm_account: "plant_lewontin_paradox"
    runtime: 720 # (In minutes)
    cpus_per_task: 16
  
  sfs_na:
    mem_mb: attempt * 20000
    slurm_partition: "fast"
    slurm_account: "plant_lewontin_paradox"
    runtime: 720 # (In minutes)
    cpus_per_task: 16

  gene_density:
    mem_mb: attempt * 20000
    slurm_partition: "fast"
    slurm_account: "plant_lewontin_paradox"
    runtime: 240 # (In minutes)
    cpus_per_task: 2
