executor: slurm
use-conda: True
jobs: 50 # Have up to N jobs submitted at any given time
latency-wait: 200 # Wait N seconds for output files due to latency
retries: 1 # Retry jobs N times.

# These resources will be applied to all rules. Can be overriden on a per-rule basis below.
default-resources:
  mem_mb: attempt * 10000
  slurm_partition: "ecobio,genouest"
  slurm_account: "mbrault"
  runtime: 480 # (In minutes)
  cpus_per_task: 2

set-resources:
  sfs_projection:
    mem_mb: attempt * 50000
    slurm_partition: "ecobio,genouest"
    slurm_account: "mbrault"
    runtime: 1440 # (In minutes)
    cpus_per_task: 16
  
  sfs:
    mem_mb: attempt * 50000
    slurm_partition: "ecobio,genouest"
    slurm_account: "mbrault"
    runtime: 1440 # (In minutes)
    cpus_per_task: 16
  
  callability_sfs_projection:
    mem_mb: attempt * 50000
    slurm_partition: "ecobio,genouest"
    slurm_account: "mbrault"
    runtime: 1440 # (In minutes)
    cpus_per_task: 16

  callability_sfs_small:
    mem_mb: attempt * 50000
    slurm_partition: "ecobio,genouest"
    slurm_account: "mbrault"
    runtime: 1440 # (In minutes)
    cpus_per_task: 16

  callability_sfs_strict:
    mem_mb: attempt * 50000
    slurm_partition: "ecobio,genouest"
    slurm_account: "mbrault"
    runtime: 1440 # (In minutes)
    cpus_per_task: 16

  callability_sfs_ml:
    mem_mb: attempt * 50000
    slurm_partition: "ecobio,genouest"
    slurm_account: "mbrault"
    runtime: 1440 # (In minutes)
    cpus_per_task: 16
