executor: slurm
use-conda: True
jobs: 70 # Have up to N jobs submitted at any given time
latency-wait: 200 # Wait N seconds for output files due to latency
retries: 1 # Retry jobs N times.

# These resources will be applied to all rules. Can be overriden on a per-rule basis below.
default-resources:
  mem_mb: attempt * 2000
  slurm_partition: "ecobio,genouest"
  slurm_account: "mbrault"
  runtime: 120 # (In minutes)
  cpus_per_task: 2

set-resources:
  run_msmc2:
    mem_mb: attempt * 5000
    slurm_partition: "ecobio,genouest"
    slurm_account: "mbrault"
    runtime: 240 # (In minutes)
    cpus_per_task: 8
   
  sfs_projection:
    mem_mb: attempt * 150000
    slurm_partition: "ecobio,genouest,bigmem"
    slurm_account: "mbrault"
    runtime: 1440 # (In minutes)
    cpus_per_task: 16
  
  sfs:
    mem_mb: attempt * 150000
    slurm_partition: "ecobio,genouest,bigmem"
    slurm_account: "mbrault"
    runtime: 1440 # (In minutes)
    cpus_per_task: 16
  
  callability_sfs_projection:
    mem_mb: attempt * 100000
    slurm_partition: "ecobio,genouest,bigmem"
    slurm_account: "mbrault"
    runtime: 1440 # (In minutes)
    cpus_per_task: 16

  callability_sfs_small:
    mem_mb: attempt * 100000
    slurm_partition: "ecobio,genouest,bigmem"
    slurm_account: "mbrault"
    runtime: 1440 # (In minutes)
    cpus_per_task: 16

  callability_sfs_strict:
    mem_mb: attempt * 100000
    slurm_partition: "ecobio,genouest,bigmem"
    slurm_account: "mbrault"
    runtime: 1440 # (In minutes)
    cpus_per_task: 16

  callability_sfs_ml:
    mem_mb: attempt * 100000
    slurm_partition: "ecobio,genouest,bigmem"
    slurm_account: "mbrault"
    runtime: 1440 # (In minutes)
    cpus_per_task: 16

  density_sfs:
    mem_mb: attempt * 100000
    slurm_partition: "ecobio,genouest,bigmem"
    slurm_account: "mbrault"
    runtime: 1440 # (In minutes)
    cpus_per_task: 16
  
  density_sfs_projection:
    mem_mb: attempt * 100000
    slurm_partition: "ecobio,genouest,bigmem"
    slurm_account: "mbrault"
    runtime: 1440 # (In minutes)
    cpus_per_task: 16
  
  recombination_sfs:
    mem_mb: attempt * 100000
    slurm_partition: "ecobio,genouest,bigmem"
    slurm_account: "mbrault"
    runtime: 1440 # (In minutes)
    cpus_per_task: 16
  
  recombination_sfs_projection:
    mem_mb: attempt * 100000
    slurm_partition: "ecobio,genouest,bigmem"
    slurm_account: "mbrault"
    runtime: 1440 # (In minutes)
    cpus_per_task: 16